#steps:
#  # Install dependencies
# - name: python
#    entrypoint: pip
#    args: ["install", "-r", "requirements.txt", "--user"]
## Building docker image and pushing to Container registry
# - name: 'gcr.io/cloud-builders/docker'
#    args: [ 'build', '-t', 'gcr.io/cement123/cement_image', '.' ]
# - name: 'gcr.io/cloud-builders/docker'
#    args: ['push', 'gcr.io/cement123/cement_image']
#  images: ['gcr.io/cement123/cement_image']
## Deploy to Cloud Run
#- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#      entrypoint: gcloud
#      args:
#      - 'run'
#      - 'deploy'
#      - 'cement-strength-prediction'
#      - '--image'
#      - 'gcr.io/$PROJECT_ID/cement-strength-prediction:$COMMIT_SHA'
#      - '--region'
#      - 'asia-south1'
#    images:
#    - 'gcr.io/$PROJECT_ID/cement-strength-prediction:$COMMIT_SHA'
#    # logging



 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/SERVICE-NAME:$COMMIT_SHA', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/SERVICE-NAME:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'SERVICE-NAME'
   - '--image'
   - 'gcr.io/$PROJECT_ID/SERVICE-NAME:$COMMIT_SHA'
   - '--region'
   - 'REGION'
 images:
 - 'gcr.io/$PROJECT_ID/SERVICE-NAME:$COMMIT_SHA'
